CREATE TABLE DANGKYXE (
    TV_ID INT NOT NULL PRIMARY KEY IDENTITY,
    TV_TGBD DATETIME NOT NULL,
    TV_TGKT DATETIME NOT NULL,
    TV_NGUOICB NVARCHAR(30) NOT NULL,
	TV_NOIDI NVARCHAR(30) NOT NULL,
	TV_NOIDEN NVARCHAR(30) NOT NULL,
	TV_THANHPHAN NVARCHAR(50) NOT NULL,
	TV_SOKM INT NOT NULL,
	TV_SOGHE INT NOT NULL,
	TV_NOIDUNG NVARCHAR(50) NOT NULL,
	TV_DNVI NVARCHAR(30) NOT NULL,
	TV_GHICHU NVARCHAR(50) NOT NULL
)